version: '3.9'

services:
    database:
      container_name: menukarte-database-${type}
      image: mariadb:${mariadb_version}
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: ${db_root_password}
        MYSQL_DATABASE: ${db_database}
        MYSQL_USER: ${db_user}
        MYSQL_PASSWORD: ${db_password}
      ports:
        - "127.0.0.1:${mariadb_ext_db_port}:3306"
      volumes:
      - ../mariadb:/var/lib/mysql
    php:
      container_name: menukarte-php-${type}
      build:
        context: ../php
        dockerfile: Dockerfile
      #ports:
        #menukarte-phpfpm
        #- '9000:9000'
        #Symfony Internal
        #- '9999:9999'
      volumes:
        - ../app:/var/www/menukarte
        - ../logs/php:/var/log/php
        - ${xdebug}
        - ${errorreporting}
      depends_on:
        - menukarte-database-${type}
    nginx:
      container_name: menukarte-nginx-${type}
      image: nginx:stable-alpine
      ports:
        - "127.0.0.1:${nginx_out_port}:80"
      volumes:
        - ../app:/var/www/menukarte
        - ../nginx/default-${type}.conf:/etc/nginx/conf.d/default.conf
        - ../logs/nginx:/var/log/nginx
      depends_on:
        - menukarte-php-${type}
        - menukarte-database-${type}
#    mailhog:
#      container_name: mailhog-${type}
#      image: mailhog/mailhog:latest
#      ports:
#        - '8025:8025'
#        - '1025:1025'
networks: 
  default: 
    name: ${networkname}
